<?php

namespace App\Support;

class LegalDocuments
{
    public static function get(string $document): array
    {
        abort_unless(in_array($document, ['agreement', 'privacy'], true), 404);

        return $document === 'agreement' ? [
            'title' => 'Service Agreement',
            'intro' => 'Carbay+ is provided by Abidale Group, a company registered in Ghana, through Enabl Technologies, its software subsidiary. In this agreement, “Provider” means Abidale Group acting through Enabl Technologies; “Company” means the washing bay or other organisation using Carbay+.',
            'sections' => [
                ['Provider and contract', 'This agreement sets out proposed terms for the Company and its authorised users. A subscription order or signed service contract identifies the contracting entities, package, price and term. The individual agreeing for a Company must have authority to bind it. A signed contract prevails over conflicting terms here. Merely viewing this document does not create a record of acceptance.'],
                ['Licence and software ownership', 'The Provider grants the Company a limited, non-exclusive, non-transferable right to use Carbay+ for its own lawful business during its authorised subscription. The Provider retains ownership of the software, source code, designs, branding and related intellectual property. No purchase of a subscription transfers those rights. The Company retains rights in the business data it supplies. It grants only the rights needed to host, process, secure and support that data.'],
                ['Accounts and lawful use', 'The Company controls staff access, branch assignments, prices and worker share settings, and must promptly remove unauthorised users. Users must protect passwords and PINs. Unauthorised access, copying or resale of the software, malicious interference and unlawful use are prohibited, subject to rights that applicable law cannot exclude. The Company is responsible for the accuracy and lawful collection of its records.'],
                ['Jobs, earnings and payments', 'Carbay+ records jobs, worker earnings and payment confirmations using supplied entries and configured percentages. It does not replace a bank, employment agreement or independent accounting review. Completing a job confirms work status; confirming a worker payout records money the operator says has already been given. Verify amounts and references before confirmation. The Company remains responsible for customer receipts, wages, taxes, refunds and correcting inaccurate entries. Payment gateways and SMS providers apply their own terms.'],
                ['Subscriptions and service availability', 'Fees, renewal, cancellation and any refund entitlement follow the agreed order or signed contract and applicable law. Features may depend on the package and third-party availability. The Provider may maintain, update or suspend access to address security incidents, unlawful use or unpaid agreed fees, with reasonable notice where practical. No uninterrupted service or specific business outcome is guaranteed.'],
                ['Privacy and confidentiality', 'Each party must protect confidential information and use personal data only for lawful purposes. The Data Privacy notice describes the intended division of responsibilities. Where the Provider processes Company data on its behalf, a written processing agreement should specify instructions, security, service providers, retention, incident handling and return or deletion. These terms do not remove either party’s duties under Ghanaian law.'],
                ['Responsibility and limitations', 'To the extent permitted by law and subject to any signed contract, neither party is liable for indirect losses, and the Provider’s aggregate contractual liability is limited to the service fees paid by the Company in the preceding twelve months. This proposed limit does not exclude fraud, wilful misconduct or liability that cannot lawfully be limited, including mandatory data-protection obligations. Claims caused by unlawful Company instructions or misuse remain the Company’s responsibility, to the extent permitted by law.'],
                ['Ending service and disputes', 'On termination, the licence ends. The parties should agree a reasonable data-export and deletion process, subject to lawful retention and outstanding obligations. Ghanaian law governs this agreement, subject to mandatory applicable law. Parties should first seek a good-faith resolution; unresolved disputes may be referred to a court of competent jurisdiction in Ghana. Material changes require notice and any acceptance required by the applicable contract or law.'],
            ],
        ] : [
            'title' => 'Data Privacy',
            'intro' => 'This notice describes personal-data handling in Carbay+, provided by Abidale Group through its software subsidiary Enabl Technologies. It covers company administrators, managers, workers and clients, and should be read alongside the washing bay’s own privacy notice.',
            'sections' => [
                ['Who is responsible', 'The Company ordinarily determines why its staff and customer records are collected and how they are used. The Provider processes those records to deliver the service under Company instructions, and determines the use of its own subscription, support and security records. Actual controller and processor responsibilities depend on the activities and agreement. Ghana’s Data Protection Act, 2012 (Act 843) governs applicable processing; company incorporation alone is not proof of registration with the Data Protection Commission.'],
                ['Information handled', 'Records may include names, phone numbers, email addresses, branch and account roles, profile photographs, vehicle registration plates, optional job images, services, bookings, prices, payment references, worker shares, wallet entries, payouts and activity logs. Sessions, network information and security logs support access and troubleshooting. Passwords and PINs are stored as hashes. A payment gateway processes payment details through its own service. Avoid uploading sensitive personal information unrelated to the job.'],
                ['Purposes and choices', 'Data supports account access, work assignment, sales records, earnings and payouts, client service, subscriptions, security and support. Processing must have a lawful basis appropriate to the activity, including contractual necessity, a legal obligation, an applicable legitimate interest or consent where required. The Company must inform staff and clients about its collection and use. Optional profile photos, job images and client details are not required for a basic walk-in job; core account, job and payment information is needed for the associated functions.'],
                ['Camera, OCR and device storage', 'Camera or photo access is used when a user chooses capture, upload or plate scanning. The live scanner recognises text on the device and loads recognition software from a third-party content-delivery network. Confirmed plates and any deliberately submitted images become job records. A separately configured server OCR service may receive submitted plate images. Browser sessions maintain sign-in; the installed web app stores basic assets locally. Sensitive dashboards are not intentionally cached for offline use.'],
                ['Who may receive data', 'Access follows company and branch roles and each worker’s account. Authorised support or platform administration may access records for service delivery, security or troubleshooting. Configured payment, SMS, OCR, hosting and infrastructure providers receive data necessary for their functions. Some providers may process data outside Ghana; applicable protections and processing terms must be assessed before use. Data may be disclosed when legally required. Personal data is not to be sold or used for unrelated advertising.'],
                ['Security, retention and incidents', 'The application uses authentication, PIN hashing and access controls; these require appropriate hosting, HTTPS, restricted administration and operational safeguards. Data must be retained only as necessary for service delivery, lawful accounting, disputes or other permitted purposes. Detailed retention and backup-deletion schedules should be agreed with the Company; no automatic deletion period is promised here. Security incidents require investigation and notifications to affected parties and the regulator where applicable law requires them.'],
                ['Your rights and requests', 'Subject to applicable law and exceptions, individuals may request information about processing, access to their data, correction, and deletion or objection where applicable. Consent may be withdrawn for consent-based processing without invalidating earlier lawful processing. Contact the Company first for its staff or client records, or contact the Provider for subscription, support or security records. Identity verification may be required. You may raise unresolved privacy concerns with Ghana’s Data Protection Commission.'],
                ['Updates and contact', 'The version below identifies this notice. Material changes should be communicated through appropriate service channels. Rights requests must be considered under applicable law; using the platform does not waive privacy rights or automatically consent to marketing. Provider contact details are listed below when configured.'],
            ],
        ];
    }
}
